document.addEventListener("DOMContentLoaded",()=>{if(!schoolAuth.requireRole("principal"))return;$("#logoutBtn")?.addEventListener("click",schoolAuth.logout);$("#admissionForm")?.addEventListener("submit",admit);$("#studentSearchForm")?.addEventListener("submit",e=>{e.preventDefault();students()});$("#teacherForm")?.addEventListener("submit",teacher);$("#principalForm")?.addEventListener("submit",principal);$("#feePaymentForm")?.addEventListener("submit",fee);$("#marksForm")?.addEventListener("submit",marks);$("#resultSearchForm")?.addEventListener("submit",result);$("#examForm")?.addEventListener("submit",exam);$("#noticeForm")?.addEventListener("submit",notice);$("#schoolSettingsForm")?.addEventListener("submit",settings);students();teachers();principals();fees();notices();exams();});
const $=s=>document.querySelector(s);
async function admit(e){e.preventDefault();try{let o=Object.fromEntries(new FormData(e.target));let d=await schoolAuth.api("/students/admission",{method:"POST",body:JSON.stringify(o)});alert("Admission successful: "+d.student.admissionNumber);e.target.reset()}catch(x){alert(x.message)}}
async function students(){if(!$("#studentsTableBody"))return;try{let q=new URLSearchParams();let s=$("#studentSearch")?.value;if(s)q.set("search",s);let d=await schoolAuth.api("/students?"+q);$("#studentsTableBody").innerHTML=d.students.map(x=>`<tr><td>${schoolAuth.esc(x.admission_number)}</td><td>${schoolAuth.esc(x.student_name)}</td><td>${schoolAuth.esc(x.father_name)}</td><td>${x.class_name}</td><td>${x.section}</td><td>${x.roll_number||""}</td></tr>`).join("")}catch{}}
async function teacher(e){e.preventDefault();try{await schoolAuth.api("/teachers",{method:"POST",body:JSON.stringify({name:$("#teacherName").value,userId:$("#teacherUserId").value,password:$("#teacherPassword").value,email:$("#teacherEmail").value,phone:$("#teacherPhone").value})});e.target.reset();teachers()}catch(x){alert(x.message)}}
async function teachers(){if(!$("#teachersTableBody"))return;try{let d=await schoolAuth.api("/teachers");$("#teachersTableBody").innerHTML=d.teachers.map(x=>`<tr><td>${x.name}</td><td>${x.user_id}</td><td>${x.email||""}</td><td>${x.status}</td></tr>`).join("")}catch{}}
async function principal(e){e.preventDefault();try{await schoolAuth.api("/principals",{method:"POST",body:JSON.stringify({name:$("#principalName").value,userId:$("#principalUserId").value,password:$("#principalPassword").value,email:$("#principalEmail").value,phone:$("#principalPhone").value})});e.target.reset();principals()}catch(x){alert(x.message)}}
async function principals(){if(!$("#principalsTableBody"))return;try{let d=await schoolAuth.api("/teachers");$("#principalsTableBody").innerHTML=d.principals.map(x=>`<tr><td>${x.name}</td><td>${x.user_id}</td><td>${x.email||""}</td><td>${x.status}</td></tr>`).join("")}catch{}}
async function fee(e){e.preventDefault();try{let d=await schoolAuth.api("/fees/pay",{method:"POST",body:JSON.stringify({studentId:+$("#feeStudentId").value,amountPaid:+$("#amountPaid").value,paymentPeriod:$("#paymentPeriod").value,paymentMode:$("#paymentMode").value})});alert("Receipt: "+d.payment.receiptNumber);fees()}catch(x){alert(x.message)}}
async function fees(){if(!$("#feesTableBody"))return;try{let d=await schoolAuth.api("/fees");$("#feesTableBody").innerHTML=d.payments.map(x=>`<tr><td>${x.receipt_number}</td><td>${x.student_name}</td><td>₹${x.amount_paid}</td><td>${x.payment_mode}</td><td>${x.payment_date}</td></tr>`).join("")}catch{}}
async function exam(e){e.preventDefault();try{await schoolAuth.api("/exams",{method:"POST",body:JSON.stringify({name:$("#examName").value,academicSession:$("#examSession").value,startDate:$("#examStart").value,endDate:$("#examEnd").value})});e.target.reset();exams()}catch(x){alert(x.message)}}
async function exams(){if(!$("#examsTableBody"))return;try{let d=await schoolAuth.api("/exams");$("#examsTableBody").innerHTML=d.exams.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td>${x.academic_session}</td><td>${x.published?"Yes":"No"}</td></tr>`).join("")}catch{}}
async function marks(e){e.preventDefault();try{await schoolAuth.api("/marks",{method:"POST",body:JSON.stringify({studentId:+$("#marksStudentId").value,examId:+$("#marksExamId").value,subjectId:+$("#marksSubjectId").value,obtainedMarks:+$("#obtainedMarks").value})});alert("Marks saved")}catch(x){alert(x.message)}}
async function result(e){e.preventDefault();try{let a=$("#resultAdmissionNumber").value.trim(),r=$("#resultRollNumber").value.trim();let d=await fetch(API_BASE_URL+"/results/search?"+(a?"admissionNumber="+encodeURIComponent(a):"rollNumber="+encodeURIComponent(r)));let x=await d.json();if(!d.ok)throw Error(x.message);$("#resultData").innerHTML=`<h3>${x.student.studentName}</h3>`+x.results.map(z=>`<p>${z.examination}: ${z.obtainedMarks}/${z.totalMarks} — ${z.percentage}% — ${z.grade} — ${z.result}</p>`).join("")}catch(x){$("#resultData").textContent=x.message}}
async function notice(e){e.preventDefault();try{await schoolAuth.api("/notices",{method:"POST",body:JSON.stringify({title:$("#noticeTitle").value,description:$("#noticeDescription").value,published:$("#noticePublished").value==="true"})});e.target.reset();notices()}catch(x){alert(x.message)}}
async function notices(){if(!$("#noticesTableBody"))return;try{let d=await schoolAuth.api("/notices");$("#noticesTableBody").innerHTML=d.notices.map(x=>`<tr><td>${x.title}</td><td>${x.notice_date||""}</td><td>${x.published?"Published":"Draft"}</td></tr>`).join("")}catch{}}
async function settings(e){e.preventDefault();try{await schoolAuth.api("/settings",{method:"PUT",body:JSON.stringify({schoolName:$("#schoolName").value,board:$("#schoolBoard").value,affiliationNumber:$("#affiliationNumber").value,schoolCode:$("#schoolCode").value,academicSession:$("#academicSession").value,principalName:$("#principalName").value,vicePrincipalName:$("#vicePrincipalName").value,address:$("#schoolAddress").value,city:$("#schoolCity").value,state:$("#schoolState").value,pinCode:$("#schoolPin").value,phone:$("#schoolPhone").value,email:$("#schoolEmail").value})});alert("Settings saved")}catch(x){alert(x.message)}}